spring:
  application:
    name: "catalogue"

catalogue:
  description: "Catalogue PROD API for Queens Closet Application"
  contact:
    name: "Shouvik Sarkar 123"
    email: "shouvik@qc.com"
  onCallSupport:
    - "+919477422708"
    - "+447741946867"

build:
  version: 1.5.0
  owner: "Queenscloset  PROD Team"
